services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: always

  ml-service:
    build: ./ml-service
    container_name: ml-service
    ports:
      - "5000:5000"
    env_file:
      - ./ml-service/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    restart: always
